<!--
 * @Author: lu
 * @Date: 2020-09-16 15:14:30
 * @LastEditTime: 2020-09-16 15:42:39
 * @FilePath: \Promise\09_async和await.html
 * @Description: 
-->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>09_async和await</title>
</head>

<body>
    <script>
        /*
        1. async 函数
           函数的返回值为promise对象
           promise对象的结果由async函数执行的返回值决定
        2. await 表达式
           await右侧的表达式 一般为promise对象，单也可以是其它的值
           如果表达式是promise对象，await返回的是promise成功的值
           如果表达式是其它值，直接将此值作为await的返回值
        3. 注意：
           await必须写在async函数中，但async函数中可以没有await
           如果await的promise失败了，就会抛出异常，需要通过try...chatch来捕获处理
        */
        async function fn1() {
            //return 1
            // 返回一个Promise对象（PromiseStatus为resolved，PromiseValue为1）
            // throw 2
            // 返回一个Promise对象（PromiseStatus为rejected，PromiseValue为2）
            // return Promise.resolve(3)
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    // resolve(4)
                    reject(7)
                }, 1000)
            })
        }
        const result = fn1()
        // console.log(result)
        result.then(
            value => {
                console.log('result', value);
            },
            reason => {
                console.log('result', reason);
            }
        )
        function f2() {
            return Promise.resolve(5)
        }
        async function f3() {
            const value = await f2() // await右侧表达式为promise，得到的结果就是promise成功的value
            // const value = await 6    // await右侧表达式不是promise，得到的结果就是它本身

            try {
                const value2 = await fn1()
            } catch (error) {
                console.log('await result1', error);
            }
            console.log('await result', value);

        }
        f3();

    </script>
</body>

</html>